/*
 * This source file was generated by the Gradle 'init' task
 */
package learn.sqlite;

import learn.sqlite.rfid.Rfid;
import learn.sqlite.rfid.RfidRepository;
import learn.sqlite.rfid.RfidService;

public class App {

    public static void main(String[] args) throws Exception {
        SchemaInitializer.run();

        final RfidRepository repository = new RfidRepository();
        final RfidService service = new RfidService(repository);
        // service.save("A3F91B2C", "Ivan");
        
        final Rfid rfid = service.findByCardUid("A3F91B2C");
        System.out.println("cardUid: " + rfid.getCardUid());
        System.out.println("ownerName: " + rfid.getOwnerName());
    }

}
